AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to create an multi node Amazon Redshift cluster with the required RedshiftParameterGroup, SubnetGroup and IAM Roles.
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: General Configuration
        Parameters:
          - Env
          - Application
      - Label:
          default: Network Information
        Parameters:
          - VPC
          - SubnetID
      - Label:
          default: Redshift Cluster Information
        Parameters:
          - RedshiftClusterName
          - RedshiftClusterType
          - RedshiftNumberOfNodes
          - RedshiftNodeType
          - RedshiftMasterUsername
          - RedshiftSnapshotRetentionPeriod
          - RedshiftMaintenanceWindow
          - EDHRedshiftUserPasswordPSName
          - EDHRedshiftUserPasswordPSNameVersion
          - EDHRedshiftPublicAccess
          - EDHRedshiftPort         
      - Label:
          default: S3 Bucket Information
        Parameters:
          - EDHBucketName            
      - Label:
          default: Encrypted Cluster
        Parameters:
          - EDHRedshiftEncryptCluster          
      - Label:
          default: Redshift Cluster SecurityGroup Configuration
        Parameters:
          - EDHTABSubnetCIDR
          - EDHINFSubnetCIDR
          - EDHEMRSubnetCIDR       
      - Label:
          default: Tagging Configuration
        Parameters:
          - EDHTCOTagKey
          - EDHTCOTagValue 
Parameters:
  Application:
    Description: Tiffany Application Name
    Type: String
    Default: EDH   
  RedshiftClusterType:
    Description: The type of cluster
    Type: String
    Default: multi-node
    AllowedValues:
    - single-node
    - multi-node
  RedshiftNumberOfNodes:
    Description: The number of compute nodes in the cluster. For multi-node clusters,
      the NumberOfNodes parameter must be greater than 1
    Type: Number
    Default: '3'
  RedshiftNodeType:
    Description: The type of node to be provisioned
    Type: String
    Default: dc2.large
  RedshiftMasterUsername:
    Description: The user name that is associated with the master user account for
      the cluster that is being created
    Type: String
    Default: master
    AllowedPattern: "([a-z])([a-z]|[0-9])*"
  RedshiftClusterName:
    Description: The unique identifier for the cluster.
    Type: String
    Default: amzlrsedht01  
  RedshiftSnapshotRetentionPeriod:
    Description: The number of days the automated snapshots needs to be retained.
    Type: 'String'
    MinLength: 1
    MaxLength: 3
    Default: '20'
  RedshiftMaintenanceWindow:
    Description: The weekly time range during which automated cluster maintenance can occur.
    Type: 'String'
    Default: 'sun:07:00-sun:08:00' 
  Env:
    Description: 'The type of environment? ex: Dev/QA/Stg/Prod/Test/NonProd'
    Type: String
    MinLength: '1'
    MaxLength: '20'
    AllowedValues:
      - PROD
      - TEST
      - STG
      - DEV
      - QA
    Default: STG  
  VPC:
    Type: AWS::EC2::VPC::Id
    Description: The physical ID of the VPC
  SubnetID:
    Type: AWS::EC2::Subnet::Id
    Description: The physical ID of the Subnet for the Redshift Cluster 
  EDHBucketName:
    Type: String
    Description: Name of the EDH Bucket
    AllowedPattern: 'amzs3[a-z0-9-]*'
    Default: amzs3edhtest    
  EDHRedshiftUserPasswordPSName:
    Type: AWS::SSM::Parameter::Name  
    Description: Parameter Store Name for the Redshift Cluster Master user Password
  EDHRedshiftUserPasswordPSNameVersion:
    Type: Number  
    Description: Parameter Store Version for the Redshift Cluster Master user Password 
    Default: 1   
  EDHRedshiftEncryptCluster:
    Description: Redshift Cluster encryption
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'   
  EDHRedshiftPublicAccess:
    Description: Redshift Cluster Allow Public Access
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'       
  EDHRedshiftPort:
    Type: String
    Description: Oracle RDS Port Number
    Default: '5439'         
  EDHTABSubnetCIDR:
    Description: TABLEAU Subnet CIDR
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: '10.193.108.0/24'
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.        
  EDHINFSubnetCIDR:
    Description: INF Subnet CIDR
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: '10.193.104.0/24'
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.    
  EDHEMRSubnetCIDR:
    Description: EMR Subnet CIDR
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: '10.193.100.0/24'
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.  
  EDHTCOTagKey:
    Type: String
    Description: EDH TCO Tag Key     
  EDHTCOTagValue:
    Type: String
    Description: EDH TCO Tag Value                     
Conditions:
  IsMultiNodeCluster:
    Fn::Equals:
    - Ref: RedshiftClusterType
    - multi-node
  RedshiftEncrypteCluster: !Equals 
    - !Ref EDHRedshiftEncryptCluster
    - 'true'      
Mappings:    
  NameMap: 
    PROD: 
      lowecase: "prod"
    TEST: 
      lowecase: "test"
    STG: 
      lowecase: "stg"
    DEV: 
      lowecase: "dev"  
    QA: 
      lowecase: "qa" 
  CamelCaseMap: 
    PROD: 
      lowecase: "Prod"
    TEST: 
      lowecase: "Test"
    STG: 
      lowecase: "Stg"
    DEV: 
      lowecase: "Dev"  
    QA: 
      lowecase: "Qa"           
Resources:
  RedshiftEncryptionKey:
    Type: AWS::KMS::Key
    Condition: RedshiftEncrypteCluster
    Properties:
      Description: !Sub EDH-TCO-REDSHIFT-${Env}
      Enabled: true
      KeyPolicy:
        Version: 2012-10-17
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Join 
                - ''
                - - 'arn:aws:iam::'
                  - !Ref 'AWS::AccountId'
                  - ':root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow access for Key Administrators
            Effect: Allow
            Principal: '*'
            Action:
              - 'kms:Create*'
              - 'kms:Describe*'
              - 'kms:Enable*'
              - 'kms:List*'
              - 'kms:Put*'
              - 'kms:Update*'
              - 'kms:Revoke*'
              - 'kms:Disable*'
              - 'kms:Get*'
              - 'kms:Delete*'
              - 'kms:TagResource'
              - 'kms:UntagResource'
              - 'kms:ScheduleKeyDeletion'
              - 'kms:CancelKeyDeletion'
            Resource: '*'
          - Sid: Allow use of the key
            Effect: Allow
            Principal: '*'            
            Action:
              - 'kms:Encrypt'
              - 'kms:Decrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey*'
              - 'kms:DescribeKey'
            Resource: '*'
          - Sid: Allow attachment of persistent resources
            Effect: Allow
            Principal: '*' 
            Action:
              - 'kms:CreateGrant'
              - 'kms:ListGrants'
              - 'kms:RevokeGrant'
            Resource: '*'
            Condition:
              Bool:
                'kms:GrantIsForAWSResource': 'true'                
      Tags:
        - Key: Name
          Value: !Sub EDH-TCO-REDSHIFT-${Env}
        - Key: Environment
          Value: !Ref Env
        - Key: Application
          Value: !Ref Application          
        - Key: !Ref EDHTCOTagKey
          Value: !Ref EDHTCOTagValue 
  RedshiftEncryptionAlias:
    Type: AWS::KMS::Alias
    Condition: RedshiftEncrypteCluster
    Properties:
      AliasName: !Sub alias/EDH-REDSHIFT-${Env}
      TargetKeyId: !Ref RedshiftEncryptionKey                           
  RedshiftCluster:
    DependsOn:
      - RedshiftClusterParameterGroup
      - RedshiftClusterSubnetGroup
      - RedshiftSecurityGroup
      - RedshiftS3ReadOnlyRole
    Type: AWS::Redshift::Cluster
    Properties:
      ClusterType:
        Ref: RedshiftClusterType
      NumberOfNodes:
        Fn::If:
        - IsMultiNodeCluster
        - Ref: RedshiftNumberOfNodes
        - Ref: AWS::NoValue 
      NodeType:
        Ref: RedshiftNodeType
      ClusterIdentifier:
        Ref: RedshiftClusterName
      DBName: !FindInMap
            - NameMap
            - !Ref 'Env'
            - lowecase 
      MasterUsername:
        Ref: RedshiftMasterUsername
      MasterUserPassword: !Sub '{{resolve:ssm:${EDHRedshiftUserPasswordPSName}:${EDHRedshiftUserPasswordPSNameVersion}}}'
      ClusterParameterGroupName:
        Ref: RedshiftClusterParameterGroup
      VpcSecurityGroupIds:
        - Ref: RedshiftSecurityGroup
      ClusterSubnetGroupName:
        Ref: RedshiftClusterSubnetGroup  
      PubliclyAccessible: !Ref EDHRedshiftPublicAccess
      Port: !Ref EDHRedshiftPort
      Encrypted: !Ref EDHRedshiftEncryptCluster
      KmsKeyId: !If 
        - RedshiftEncrypteCluster
        - !Ref RedshiftEncryptionKey
        - !Ref 'AWS::NoValue'
      IamRoles: 
        - !GetAtt RedshiftS3ReadOnlyRole.Arn
        - !GetAtt RedshiftS3AccessRole.Arn
      AutomatedSnapshotRetentionPeriod: !Ref RedshiftSnapshotRetentionPeriod
      PreferredMaintenanceWindow: !Ref RedshiftMaintenanceWindow
      Tags:
        - Key: Application
          Value: !Ref Application          
        - Key: !Ref EDHTCOTagKey
          Value: !Ref EDHTCOTagValue 
        - Key: Environment
          Value: !Ref Env      
  RedshiftClusterParameterGroup:
    Type: AWS::Redshift::ClusterParameterGroup
    Properties:
      Description: Production Redshift Workload Management Group
      ParameterGroupFamily: redshift-1.0
      Parameters:
      - ParameterName: 'wlm_json_configuration'
        ParameterValue: '[{"query_concurrency":15,"max_execution_time":0,"query_group":[],"query_group_wild_card":0,"user_group":[],"user_group_wild_card":0},{"short_query_queue":true,"max_execution_time":5000}]'
      Tags:
        - Key: Application
          Value: !Ref Application          
        - Key: !Ref EDHTCOTagKey
          Value: !Ref EDHTCOTagValue 
        - Key: Environment
          Value: !Ref Env 
        - Key: Name
          Value: !Join
            - ''
            - - 'wlm-'
              - !FindInMap
                - NameMap
                - !Ref 'Env'
                - lowecase               
  RedshiftClusterSubnetGroup:
    Type: AWS::Redshift::ClusterSubnetGroup
    Properties:
      Description: Production Redshift Cluster Subnet Group
      SubnetIds: 
        - !Ref SubnetID
      Tags:
        - Key: Application
          Value: !Ref Application          
        - Key: !Ref EDHTCOTagKey
          Value: !Ref EDHTCOTagValue 
        - Key: Environment
          Value: !Ref Env 
        - Key: Name
          Value: !Join
            - ''
            - - !FindInMap
                - NameMap
                - !Ref 'Env'
                - lowecase 
              - '-edh-tco-redshift-csg'              
  RedshiftSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupName: !Sub EDH-TCO-${Env}-REDSHIFT
      GroupDescription: !Sub EDH-TCO-${Env}-REDSHIFT
      SecurityGroupIngress:
        - CidrIp: !Ref EDHTABSubnetCIDR
          IpProtocol: tcp
          FromPort: 5439
          ToPort: 5439
        - CidrIp: !Ref EDHINFSubnetCIDR
          IpProtocol: tcp
          FromPort: 5439
          ToPort: 5439
        - CidrIp: 10.192.11.196/32
          IpProtocol: tcp
          FromPort: 5439
          ToPort: 5439
        - CidrIp: 172.16.0.0/12 
          IpProtocol: tcp
          FromPort: 5439
          ToPort: 5439
        - CidrIp: 10.255.0.0/16
          IpProtocol: tcp
          FromPort: 5439
          ToPort: 5439
        - CidrIp: !Ref EDHEMRSubnetCIDR
          IpProtocol: tcp
          FromPort: 5439
          ToPort: 5439
        - CidrIp: 52.1.119.0/24
          IpProtocol: tcp
          FromPort: 5439
          ToPort: 5439  
        - CidrIp: 10.160.0.0/16
          IpProtocol: tcp
          FromPort: 5439
          ToPort: 5439                                                      
      Tags:
        - Key: Application
          Value: !Ref Application          
        - Key: !Ref EDHTCOTagKey
          Value: !Ref EDHTCOTagValue 
        - Key: Environment
          Value: !Ref Env 
        - Key: Name
          Value: !Sub EDH-TCO-${Env}-REDSHIFT
      VpcId: !Ref VPC
  RedshiftS3ReadOnlyRole:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "redshift.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess 
      RoleName: !Join
            - ''
            - - 'Redshift'
              - !FindInMap
                - CamelCaseMap
                - !Ref 'Env'
                - lowecase 
              - 'S3ReadOnlyRole'
  RedshiftS3AccessRole:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: 
                - "redshift.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/" 
      RoleName: !Join
            - ''
            - - 'Redshift'
              - !FindInMap
                - CamelCaseMap
                - !Ref 'Env'
                - lowecase 
              - 'S3'     
  RedShiftS3Policies:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: !Join
            - ''
            - - 'Redshift'
              - !FindInMap
                - CamelCaseMap
                - !Ref 'Env'
                - lowecase 
              - 'S3Policy'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
            - Sid: S3AccessPermissions
              Effect: Allow
              Action: 's3:*'
              Resource:
                - !Sub 'arn:aws:s3:::${EDHBucketName}'
                - !Sub 'arn:aws:s3:::${EDHBucketName}/*'
      Roles:
        - !Ref RedshiftS3AccessRole          
Outputs:
  RedshiftClusterEndpoint:
    Description: Redshift cluster endpoint
    Value: !GetAtt RedshiftCluster.Endpoint.Address
  RedshiftClusterName:
    Description: Redshift cluster name
    Value:
      Ref: RedshiftCluster
  RedshiftParameterGroupName:
    Description: Redshift parameter group Name
    Value:
      Ref: RedshiftClusterParameterGroup
  RedshiftClusterSubnetGroupName:
    Description: Redshift cluster subnet group name
    Value:
      Ref: RedshiftClusterSubnetGroup
  RedshiftSecurityGroupID:
    Description: Redshift Security Group ID
    Value: !GetAtt RedshiftSecurityGroup.GroupId     